
services:
  frontend_app:
    image: httpd:latest
    volumes:
      - ./front/:/usr/local/apache2/htdocs

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pg_data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_app:
    image: python
    volumes: 
      - ./app:/app
    working_dir: /app
    environment:
      DB_HOST: postgres
      DB_NAME: postgres_db
      DB_USER: user
      DB_PASSWORD: password
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    depends_on:
      - python_app
      - frontend_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

